name: PublicPlaytime
version: '${project.version}'
main: me.lifelessnerd.publicplaytime.PublicPlaytime
api-version: 1.19
authors: [ LifelessNerd ]
description: Keeps player playtime neat and public, can be shown in a number of ways in-game
website: https://github.com/LifelessNerd
commands:
  playtime:
    description: Get playtime of a player in a number of ways.
    usage: /playtime <get/ranking/scoreboard/help>
    aliases:
      - publicplaytime

